### PR TITLE
[MPMD-279] Improve documentation of maxAllowedViolations

### PR DESCRIPTION
**Pull request by adangel**
A preview of the generated documentation is available here:

~http://chunk.io/adangel/71b0f96162404038aa1a9caba662b819/site/check-mojo.html~

http://chunk.io/adangel/f7e190fce5e342b6971a7cdb1639a7f5/maven-pmd-plugin/index.html

### CODE REVIEW

**Comment by adangel** [comment]
@jbennett2091 Thanks for your comment.
I was struggling with the term "issues", since PMD only reports violations (rule violations to be specific). That's why I felt introducing a new generic term does not help but add to the confusion...but I get your point.

In short:
* Violations: PMD reports violations.
    * Each violation has a priority (1 - high, 2 - medium-high, 3 - medium, 4 - medium-low, 5 - low).
* Failures: These are violations, with a high enough priority, that we fail the build.
* Warnings: These are violations, that won't fail the build.

By default, the plugin fails the build for any violation (all violations are failures).
"failurePriority" configures, which violations are failures and which violations are warnings.
"maxAllowedViolations" controls, how many failures are needed to fail the build.
It turns out, that the property "maxAllowedViolations" should have been named actually "maxAllowedFailures", since it only checks the failure count.

I'll try to rephrase the documention with that terminologoy...

**Comment by adangel** [comment]
@jbennett2091 I've updated the descriptions. Preview is available here: http://chunk.io/adangel/f7e190fce5e342b6971a7cdb1639a7f5/maven-pmd-plugin/index.html

**Comment by jbennett2091** [comment]
I like it.

**Comment by adangel** [comment]
I've squashed and pushed it onto master -> https://github.com/apache/maven-pmd-plugin/commit/a9c5840bc258318e0e5f6c3c79db865cb9cf3f1e

Thanks for your help!

**Comment by jira-importer** [comment]
Resolve #611

**Pull request closed without merging**
