### PR TITLE
[MPMD-295] - Maven PMD Plugin fails on Java 13: Unsupported targetJdk value '13'	

### PR DESCRIPTION
**Pull request by christianhujer**
Description:
Add a test case that uses Java 13, and update the PMD dependency to 6.18.0 which works with Java 13. This way, the next release of the maven-pmd-plugin will successfully work with Java 13.

Following this checklist to help us incorporate your
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MPMD): https://issues.apache.org/jira/projects/MPMD/issues/MPMD-295
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MPMD-XXX] - Subject of the JIRA Ticket`,
       where you replace `MPMD-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by christianhujer** [comment]
Yes, and it's not a good reason. Somehow my tools (IntelliJ IDEA version autocomplete) told me that 6.18.0 is the latest version although it, in fact, is 6.20.0, as you said. Thanks a lot for noticing that! I will update the PR accordingly.

**Comment by christianhujer** [comment]
I've just tried upgrading PMD to 6.20.0. When doing that, there are test issues. I will look into that, and in parallel also try 6.19.0. I'll update here once I have more information.

**Comment by christianhujer** [comment]
I've bumped the version of PMD to 6.19.0 which passes `mvn -Prun-its verify` without regression.
When bumping to version `6.20.0`, there is a regression that needs further inspection. I will look into that regression, but it may take a few days until I can do so and present results.

**Comment by adangel** [comment]
In that case, I'd suggest to do the upgrade separately and only upgrade to 6.19.0 for now. I'll have a look into the issue as well.

**Comment by adangel** [comment]
> When bumping to version 6.20.0, there is a regression that needs further inspection. I will look into 
> that regression, but it may take a few days until I can do so and present results.

It turns out, that's actually a bug in PMD itself: https://github.com/pmd/pmd/issues/2212

**Comment by jira-importer** [comment]
Resolve #626

**Comment by jira-importer** [comment]
Resolve #626

**Pull request merged**
