### PR TITLE
Revert upgrade to 6.26

### PR DESCRIPTION
**Pull request by pzygielo**
I propose to revert recent upgrade to 6.26 (due to pmd/pmd#2663).
I suggest new IT, to test configured PMD against project with some provided dependency.
Build of proposed commits:
:heavy_check_mark:  First commit - new IT based on previous version with PMD 6.23
:red_circle: Merge update of PMD to 6.26
:heavy_check_mark: Revert PMD update

@adangel please take a look

### CODE REVIEW

**Comment by pzygielo** [comment]
If accepted - I can rebase and reopen #25, as 6.25.0 works fine.

**Comment by adangel** [comment]
If we were to release m-pmd-p, I'd agree, that this is a blocker and needs to be reverted.
I'm not sure, if adding a IT in m-pmd-p for a bug in PMD makes sense. The test case is very, very specific and would only trigger on this special case (UnusedImport)...

**Comment by pzygielo** [comment]
@adangel thanks for checking

> I'm not sure, if adding a IT in m-pmd-p for a bug in PMD makes sense.

Now I see it. You're right - such IT doesn't fit here.

**Comment by pzygielo** [comment]
Closing - as revert - should it be decided to do so - can be performed directly on GH without additional commits.

**Pull request closed without merging**
