### PR TITLE
Remove vestigial useJava5 parameter

### PR DESCRIPTION
**Pull request by elharo**
There are warnings in the build about this.

### CODE REVIEW

**Comment by elharo** [comment]
Not sure if the build is broken at head or just flaky.

**Comment by elharo** [comment]
Possibly Verify / Verify / ubuntu-latest jdk-11-temurin 3.9.1 (push) is broken at head. Going to try with something else.

**Comment by elharo** [comment]
Error:  Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.21.0-SNAPSHOT:check (default) on project MPMD-270-325-JDK11: You have 1 PMD violation. For more details see: /home/runner/work/maven-pmd-plugin/maven-pmd-plugin/target/it/MPMD-270-325-JDK11/target/pmd.xml -> [Help 1]
Error:  

This is the same error we see on #117 so I assume that test is broken there somehow

**Review by michael-o — APPROVED** [review]

**Comment by elharo** [comment]
I don't understand why some of the CI checks get cancelled. This seems a routine occurrence though. At least none are failing.

**Pull request merged**
