### PR TITLE
[MPMD-330] [MPMD-331] Upgrade Maven Parent to 35 and Require Maven 3.2.5+

### PR DESCRIPTION
**Pull request by adangel**
Fixes
* https://issues.apache.org/jira/browse/MPMD-330
* https://issues.apache.org/jira/browse/MPMD-331

Following this checklist to help us incorporate your
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MPMD) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue.  Your pull request should address just this issue, without
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MPMD-XXX] - Subject of the JIRA Ticket`,
       where you replace `MPMD-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Review by slawekjaranowski — COMMENTED** [review]
Please override:
- taglist-plugin to 3.0.0
- pmd-plugin to 3.16.0 if not use your version 😄 
- compiler-p to 3.10.1

and remove l10n-maven-plugin it not working with new m-site-p

Pleas check site output with reporting profile

**Comment by slawekjaranowski** [comment]
You can download site result from GH https://github.com/apache/maven-pmd-plugin/actions/runs/2008351825

**Comment by adangel** [comment]
@slawekjaranowski  Thanks for the review!

> if not use your version

I've not tried this - the build would probably fail if the snapshot is not already available in the local repo or snapshots. And for releases I guess, it definitively will miss the version and fail the build....

**Comment by slawekjaranowski** [comment]
@adangel please look at build log of site .. I see:
```
[INFO] Generating "CPD" report                  --- maven-pmd-plugin:3.17.0-SNAPSHOT:cpd
[INFO] Generating "PMD" report                  --- maven-pmd-plugin:3.17.0-SNAPSHOT:pmd
```

So I suppose that you use current version of plugin in site build ...
I only look at logs...

There is a hen and egg problems 😄

**Comment by adangel** [comment]
> So I suppose that you use current version of plugin in site build ... I only look at logs...
> 
> There is a hen and egg problems smile

That's true for the site - there indeed the latest version is used. But not for the verify lifecycle.

When releasing, I generate the site after the release in a separate maven run. So this works :)

**Comment by jira-importer** [comment]
Resolve #300

**Comment by jira-importer** [comment]
Resolve #300

**Pull request merged**
