### PR TITLE
[MPMD-302] - Upgrade to PMD 6.25.0

### PR DESCRIPTION
**Pull request by pzygielo**
With [Version 3.14.0](https://issues.apache.org/jira/projects/MPMD/versions/12346940) still unreleased I believe this change could be covered by existing [MPMD-302](https://issues.apache.org/jira/browse/MPMD-302).

### CODE REVIEW

**Comment by adangel** [comment]
@pzygielo sorry, already done :) -> https://github.com/apache/maven-pmd-plugin/commit/98cf3a58363a382659dd43686bde8205692eca58

**Comment by adangel** [comment]
Then plan is, that we add support for JDK15 with the next PMD version (6.27.0). I think, after that, it would be a good time to also create a new release of m-pmd-p. wdyt?

**Comment by pzygielo** [comment]
@adangel Thanks for checking.
As for new release - I myself sometimes use explicit m-pmd-p goals from commandline (I mean - when plugin is not configured in project). That's why I PRed PMD updates :smile: (as I see no way to override pmd version in such case). So new official plugin will for sure be welcomed by me.

**Comment by jira-importer** [comment]
Resolve #331

**Comment by jira-importer** [comment]
Resolve #331

**Pull request closed without merging**
