### PR TITLE
[MNG-6825] Replace StringUtils with Commons Lang3

### PR DESCRIPTION
**Pull request by timtebeek**

### CODE REVIEW

**Review by elharo — APPROVED** [review]

**Comment by elharo** [comment]
The failing build is likely broken already. I'm looking into it.

**Review by elharo — COMMENTED** [review]
Please rebase. The failing CI should now pass, and then we'll be good to go.

**Comment by timtebeek** [comment]
Resolved the conflicts, but I assume we'll want to first remove the `StringUtils.is(Not)Empty/Blank`, which will likely result in unused imports here.

**Comment by elharo** [comment]
I don't think we have to remove StringUtils.is(Not)Empty/Blank first, though it's fine if someone wants to do that.

**Comment by timtebeek** [comment]
Looks like we'll move away from commons-lang3 instead; https://issues.apache.org/jira/browse/MNG-6829
Closing this one in favor of changes such as [replacing StringUtils.isEmpty/isNotEmpty with JDK internals](https://public.moderne.io/recipes/org.openrewrite.java.migrate.apache.commons.lang.IsNotEmptyToJdk?).

**Comment by elharo** [comment]
JDK > commons-lang3 > maven-shared-utils > plexus-utils

If we can go straight to JDK only, wonderful, but I'd still approve a PR that replaces plexus with commons lang.

**Comment by timtebeek** [comment]
Would you like to see this recreated now that we have https://github.com/apache/maven-pmd-plugin/commit/40fe4444ea805e76b77446742c4278fabd7aff51 merged in? It'd swap even fewer imports, with no new dependency as commons-lang3 is already a dependency. https://github.com/apache/maven-pmd-plugin/blob/40fe4444ea805e76b77446742c4278fabd7aff51/pom.xml#L148-L150

**Comment by elharo** [comment]
sure, if this is still relevant, do it

**Pull request closed without merging**
